/**
 * Catálogo de códigos de error.
 *
 * El `code` es parte del contrato: el frontend decide qué mostrar según él, no
 * según el texto. Agregar uno es aditivo; cambiar el significado de uno
 * existente rompe clientes.
 */
export const ErrorCode = {
  // Genéricos
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFLICT: 'CONFLICT',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  GYM_SUSPENDED: 'GYM_SUSPENDED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  CSRF_INVALID: 'CSRF_INVALID',

  // Autorización
  FORBIDDEN: 'FORBIDDEN',
  MISSING_PERMISSION: 'MISSING_PERMISSION',
  FEATURE_NOT_ENABLED: 'FEATURE_NOT_ENABLED',
  BRANCH_NOT_ALLOWED: 'BRANCH_NOT_ALLOWED',
  PLAN_LIMIT_REACHED: 'PLAN_LIMIT_REACHED',

  // Tenancy e IAM (API_CONTRACTS §4/§5) — mismos strings que
  // packages/contracts/src/common.ts (ERROR_CODES), que es el catálogo que
  // valida el frontend.
  BRANCH_HAS_ACTIVE_DATA: 'BRANCH_HAS_ACTIVE_DATA',
  LAST_OWNER: 'LAST_OWNER',

  // Idempotencia
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',

  // Socios
  DUPLICATE_DOCUMENT: 'DUPLICATE_DOCUMENT',
  DUPLICATE_CARD: 'DUPLICATE_CARD',
  MEMBER_HAS_DEBT: 'MEMBER_HAS_DEBT',
  MEMBER_INACTIVE: 'MEMBER_INACTIVE',

  // Catálogo y membresías
  PLAN_IN_USE: 'PLAN_IN_USE',
  ACTIVITY_IN_USE: 'ACTIVITY_IN_USE',
  MEMBERSHIP_OVERLAP: 'MEMBERSHIP_OVERLAP',
  MEMBERSHIP_NOT_ACTIVE: 'MEMBERSHIP_NOT_ACTIVE',

  // Caja
  NO_OPEN_CASH_SESSION: 'NO_OPEN_CASH_SESSION',
  CASH_SESSION_ALREADY_OPEN: 'CASH_SESSION_ALREADY_OPEN',
  CASH_REGISTER_BUSY: 'CASH_REGISTER_BUSY',
  USER_HAS_OPEN_SESSION: 'USER_HAS_OPEN_SESSION',
  CASH_SESSION_HAS_PENDING_OPERATIONS: 'CASH_SESSION_HAS_PENDING_OPERATIONS',
  CASH_SESSION_CLOSED: 'CASH_SESSION_CLOSED',
  MOVEMENT_ALREADY_REVERSED: 'MOVEMENT_ALREADY_REVERSED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  OPERATION_ALREADY_RESOLVED: 'OPERATION_ALREADY_RESOLVED',

  // Acceso
  ACCESS_INPUT_INVALID: 'ACCESS_INPUT_INVALID',

  // Biometría (§10) — mismos strings que packages/contracts/src/common.ts
  NO_BIOMETRIC_CONSENT: 'NO_BIOMETRIC_CONSENT',
  FINGER_ALREADY_ENROLLED: 'FINGER_ALREADY_ENROLLED',
  AGENT_OFFLINE: 'AGENT_OFFLINE',
  INVALID_DEVICE_TOKEN: 'INVALID_DEVICE_TOKEN',
  AGENT_REVOKED: 'AGENT_REVOKED',
  TEMPLATE_QUALITY_TOO_LOW: 'TEMPLATE_QUALITY_TOO_LOW',
  /** Las muestras del mismo enrolamiento no se reconocen entre sí. */
  ENROLLMENT_SAMPLES_INCONSISTENT: 'ENROLLMENT_SAMPLES_INCONSISTENT',
  /** El servicio SourceAFIS no respondió: se registra el intento y se avisa. */
  BIOMETRIC_MATCHER_UNAVAILABLE: 'BIOMETRIC_MATCHER_UNAVAILABLE',

  // Mensajería
  MESSAGING_NOT_CONFIGURED: 'MESSAGING_NOT_CONFIGURED',
  BROADCAST_CONFIRMATION_REQUIRED: 'BROADCAST_CONFIRMATION_REQUIRED',

  // Storage
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
